workflow:
  rules:
    - if: $CI_MERGE_REQUEST_APPROVED
    - if: $CI_COMMIT_BRANCH == 'develop'
default:
  retry: 1

stages:
  - build
  - deploy

variables:
  VERSION: $CI_COMMIT_SHORT_SHA
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  ECR_URL: $ECR_URL
  ECR_BATCH_IMAGE_URL: $ECR_URL/$ECR_REPO_NAME

build-job:
  stage: build
  variables:
    RUNNER_SCRIPT_TIMEOUT: 30m
    RUNNER_AFTER_SCRIPT_TIMEOUT: 10m
  script:
    - echo "Checkout develop branch"
    - git checkoutdevelop
    - echo "...Build & push batch image to ECR"
    - ./build_script.sh

deploy-job:
  stage: deploy
  script:
    - ./deploy.sh
  after_script:
    - rm -fr $CI_PROJECT_DIR
